package cc.darhao.farm.mapper;

import cc.darhao.farm.entity.Production;
import cc.darhao.farm.entity.ProductionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int countByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int deleteByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    List<Production> selectByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    Production selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int updateByExample(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated Wed Apr 11 22:04:25 CST 2018
     */
    int updateByPrimaryKey(Production record);
}